#!/bin/bash
#SBATCH -p gpu-he --gres=gpu:2 --constraint=a6000
#SBATCH --mem=128G
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 48:00:00

export CUR_DIR=/users/inguyen4/code/cs2952w/representational-harms-nationality-llms


module load cuda/12.1
# conda
. "/gpfs/runtime/opt/anaconda/2022.05/etc/profile.d/conda.sh"

conda activate chi

cd $CUR_DIR

. main.py